#'原名' = [ '译名', 出现次数 ]

"花丸" = ["花丸", 3277]
"エレナ" = ["艾琳娜", 2172]
"ルナ" = ["露娜", 2131]
"青山" = ["青山", 512]
"風丸" = ["风丸", 458]
"樹里" = ["树里", 442]
"親父" = ["老爹", 233]
"京子" = ["京子", 153]
"宗彦" = ["宗彦", 152]
"英一郎" = ["英一郎", 140]
"ありさ" = ["亚里沙", 133]
"鮎川" = ["鲇川", 68]
"女性" = ["女性", 8]
"北条" = ["北条", 7]
"男" = ["男人", 7]
"女の子" = ["女孩子", 5]
"友達" = ["朋友", 5]
"医者" = ["医生", 4]
"仲間" = ["同伴", 3]
"アナウンサー" = ["播音员", 1]
"看護婦" = ["护士", 1]
"青年" = ["青年", 1]
"後輩" = ["后辈", 1]
"変態" = ["变态", 1]
"教官" = ["教师", 1]
"老人" = ["老人", 1]
