# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)
gptDict = [
    # 语义标注

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },


    # 主要角色
    { org = "花丸", rep = "花丸", note = "人名，男性，全名‘狮子堂花丸’（獅子堂 花丸，ししどう はなまる），兰山大学一年级生（因为两次复读导致才大一，实际应该大三），主人公，风丸的双胞胎哥哥，露娜的表哥，老实、正直、有点天然呆、容易说出土味情话、对喜欢的人非常执着、情绪化，母亲因事故去世" },
    { org = "獅子堂花丸", rep = "狮子堂花丸", note = "人名全名，男性，即‘花丸’" },
    { org = "花丸くん", rep = "花丸君", note = "人名，男性，花丸的称呼" },
    { org = "お兄ちゃん", rep = "哥哥", note = "人名，男性，露娜对花丸的称呼" },
    { org = "類似品", rep = "山寨货", note = "人名，男性，京子对花丸的称呼（贬义，表示是风丸的代替品）" },
    { org = "獅子堂Ｂ", rep = "狮子堂Ｂ", note = "人名，男性，京子对花丸的称呼（贬义）" },

    { org = "風丸", rep = "风丸", note = "人名，男性，全名‘狮子堂风丸’（獅子堂 風丸，ししどう かぜまる），兰山大学三年级生，花丸的双胞胎弟弟，树里的男友，保龄球部成员，冷静、毒舌、有点冷淡、保护欲强（对哥哥）、对感情事看得比较透彻，体育成绩优异，受欢迎" },
    { org = "獅子堂風丸", rep = "狮子堂风丸", note = "人名全名，男性，即‘风丸’" },
    { org = "風丸くん", rep = "风丸君", note = "人名，男性，风丸的称呼" },
    { org = "獅子堂Ａ", rep = "狮子堂Ａ", note = "人名，男性，京子对风丸的称呼（贬义）" },
    { org = "風丸お兄ちゃん", rep = "风丸哥哥", note = "人名，男性，露娜对风丸的称呼" },

    { org = "獅子堂くん", rep = "狮子堂君", note = "人名，男性，代指花丸或是风丸（根据上下文确认）" },
    { org = "獅子堂", rep = "狮子堂", note = "人名姓氏，风丸和花丸的姓氏" },

    { org = "エレナ", rep = "艾琳娜", note = "人名，女性，全名‘北条艾琳娜’（北条 エレナ），兰山大学四年级生，保龄球部部长，毒舌、傲娇、表面强势内心脆弱、完美主义，保龄球超强，过去曾喜欢过风丸，并与树里竞争过（失败），导致对花丸感情复杂" },
    { org = "エレナさん", rep = "艾琳娜小姐", note = "人名，女性，艾琳娜的称呼" },
    { org = "エレナちゃん", rep = "小艾琳娜", note = "人名，女性，艾琳娜的称呼" },
    { org = "北条エレナ", rep = "北条艾琳娜", note = "人名全名，女性，即‘艾琳娜’" },
    { org = "北条先輩", rep = "北条前辈", note = "人名，女性，艾琳娜的称呼" },
    { org = "お局様", rep = "大姐头", note = "人名，女性，艾琳娜的称呼" },

    { org = "ありさ", rep = "亚里沙", note = "人名，女性，全名‘北条亚里沙’（北条 ありさ，ほうじょう ありさ），艾琳娜的妈妈，单亲，强势、开朗、调侃（对花丸和艾琳娜）" },
    { org = "北条ありさ", rep = "北条亚里沙", note = "人名全名，女性，即‘亚里沙’" },
    { org = "ありささん", rep = "亚里沙阿姨/亚里沙小姐", note = "人名，女性，亚里沙的称呼（如果是年轻一代，选择‘亚里沙阿姨’）" },
    { org = "ママリン", rep = "妈妈琳", note = "人名，女性，花丸和风丸对亚里沙的称呼" },

    { org = "北条", rep = "北条", note = "人名姓氏，艾琳娜和亚里沙的姓氏" },

    { org = "ルナ", rep = "露娜", note = "人名，女性，全名‘鲇川露娜’（鮎川 ルナ），复读生，花丸的表妹，儿时与双胞胎（花丸和风丸）关系亲密，元气、撒娇、有点小恶魔、胸部发育很好、对花丸有好感" },
    { org = "ルナちゃん", rep = "小露娜", note = "人名，女性，露娜的称呼" },
    { org = "鮎川ルナ", rep = "鲇川露娜", note = "人名全名，女性，即‘露娜’" },
    { org = "鮎川", rep = "鲇川", note = "人名姓氏，露娜的姓氏，通常代指露娜的母亲（花丸的姑姑，强势、浮气）" },
    { org = "カルメン", rep = "卡门", note = "人名，女性，青山对露娜的称呼" },
    { org = "カルメンちゃん", rep = "小卡门", note = "人名，女性，青山对露娜的称呼" },

    { org = "青山", rep = "青山", note = "人名姓氏，男性，全名‘青山邦彦’（青山 邦彦，あおやま くにひこ），兰山大学二年级生（比花丸早一年），花丸的中学/高中好友，轻浮、毒舌、爱开黄腔、很会玩、老好人本质、" },
    { org = "青山邦彦", rep = "青山邦彦", note = "人名全名，男性，即‘青山’" },
    { org = "邦彦", rep = "邦彦", note = "人名，男性，青山的名字" },

    { org = "英一郎", rep = "英一郎", note = "人名，男性，全名‘藤原英一郎’（藤原 英一郎，ふじわら えいいちろう），四天王大学学生，保龄球部成员，京子的弟弟，风丸的对手，冷静、毒舌" },
    { org = "藤原英一郎", rep = "藤原英一郎", note = "人名全名，男性，即‘英一郎’" },

    { org = "京子", rep = "京子", note = "人名，女性，全名‘藤原京子’（藤原 京子，ふじわら きょうこ），四天王大学四年级生，四天王大学保龄球部的主力，英一郎的姐姐，傲慢、毒舌、财阀千金气质、非常有攻击性（对艾琳娜）、喜欢炫富、与艾琳娜长期敌对" },
    { org = "藤原京子", rep = "藤原京子", note = "人名全名，女性，即‘京子’" },
    { org = "京子さん", rep = "京子小姐", note = "人名，女性，京子的称呼" },

    { org = "藤原先輩", rep = "藤原前辈", note = "人名，代指英一郎或是京子（根据上下文确认）" },
    { org = "藤原", rep = "藤原", note = "人名姓氏，英一郎和京子的姓氏" },

    { org = "樹里", rep = "树里", note = "人名，女性，全名‘今川树里’（今川 樹里，いまがわ じゅり），兰山大学四年级生，保龄球部副部长，风丸的恋人，温柔、爱操心、护短、有点八卦、艾琳娜的同期/好友" },
    { org = "今川樹里", rep = "今川树里", note = "人名全名，女性，即‘树里’" },
    { org = "樹里さん", rep = "树里小姐", note = "人名，女性，树里的称呼" },
    { org = "今川先輩", rep = "今川前辈", note = "人名，女性，树里的称呼" },
    { org = "今川", rep = "今川", note = "人名姓氏，树里的姓氏" },

    { org = "宗彦", rep = "宗彦", note = "人名，男性，全名‘铃木宗彦’（鈴木 宗彦），四天王大学学生，保龄球部成员，自大、幻想癖、易怒、变态，露娜的追求者，花丸的对手" },
    { org = "鈴木", rep = "铃木", note = "人名姓氏，宗彦的姓氏" },
    { org = "鈴木宗彦", rep = "铃木宗彦", note = "人名全名，男性，即‘宗彦’" },
    { org = "鈴木先輩", rep = "铃木前辈", note = "人名，男性，宗彦的称呼" },

    { org = "親父", rep = "老爹", note = "人名代称，男性，花丸和风丸的父亲，温和、人生经验丰富、爱开导儿子，单亲" },

    # 其他

    { org = "教官", rep = "教师", note = "职业称呼" },

    { org = "メイキング・イン・フィット", rep = "Making in Fit", note = "分球名称，入部考核用的" },
    { org = "セブンテン", rep = "七十分球", note = "保龄球术语，象征未完成的感情，多次作为隐喻。" },
    { org = "スプリット", rep = "分球", note = "保龄球术语" },
    { org = "インステップ", rep = "内步", note = "保龄球技术" },
    { org = "パーフェクト", rep = "完美局", note = "保龄球术语" },
    { org = "ストライク", rep = "全中", note = "保龄球术语" },
    { org = "ターキー", rep = "三连击", note = "保龄球连续三次全倒，比赛中关键" },
    { org = "ファウルライン", rep = "犯规线", note = "保龄球投球界线" },

    { org = "エキサイトボウリングセンター", rep = "激动保龄球中心", note = "比赛/练习场地" },

    { org = "蘭王戦", rep = "兰王战", note = "兰山大学（国立）和四天王大学（私立）的传统保龄球对抗赛" },

    { org = "反語", rep = "反语", note = "咖啡店名称，角色们聚会场所" },

    { org = "センター試験", rep = "大学入学考试", note = "入学考试" },

    { org = "山手予備校", rep = "山手补习学校", note = "露娜的复读学校" },
    { org = "山手", rep = "山手", note = "地名/车站名" },
    { org = "山手中央駅", rep = "山手中央站", note = "地名/车站名" },
    { org = "山手リーグ", rep = "山手联赛", note = "6校联赛，四天王大学9连霸，兰山大学永远第二" },

    { org = "四天王大学", rep = "四天王大学", note = "学校名，露娜和京子所就读的大学" },

    { org = "緑川高校", rep = "绿川高中", note = "学校名，主人公花丸曾就读的学校（已毕业）" },
    { org = "蘭山大学", rep = "兰山大学", note = "学校名，主人公花丸所就读的大学名" },

    { org = "ボウリング", rep = "保龄球", note = "活动名/物品名" },
    { org = "ボウリング部", rep = "保龄球部", note = "社团名" },

    { org = "先輩", rep = "前辈", note = "关系称呼" },
    { org = "後輩", rep = "后辈", note = "关系称呼" },

    { org = "新歓コンパ", rep = "新生欢迎会", note = "社团活动" },

    { org = "胡蝶蘭", rep = "蝴蝶兰", note = "花名" },

    { org = "広渡教授", rep = "广渡教授", note = "人名，男性" },
    { org = "金子", rep = "金子", note = "人名" },

    { org = "元山町", rep = "元山町", note = "地名" },
    { org = "弁天町", rep = "弁天町", note = "地名" },

    { org = "三瀬", rep = "三濑", note = "地名" },
    { org = "三瀬の海水浴場", rep = "三濑海水浴场", note = "地名" },
    { org = "大浦海岸", rep = "大浦海岸", note = "地名" },
    { org = "大浦港", rep = "大浦港", note = "地名" },
    { org = "大浦シーパレス", rep = "大浦海洋宫", note = "地名" },

    { org = "セバスチャン・オニール", rep = "塞巴斯蒂安·奥尼尔", note = "人名/品牌名" },
    { org = "シャルル・ロラン", rep = "夏尔·罗兰", note = "人名/品牌名" },
    { org = "マゾリックス", rep = "马佐里克斯", note = "电影名" },
    { org = "ウィンブルドン", rep = "温布尔登", note = "网球赛事/地名" },
    { org = "アローシュ", rep = "阿罗什", note = "外语词汇/葡萄牙语" },

    { org = "慶子", rep = "庆子", note = "人名，女性，露娜的母亲，花丸的姑姑" },

]
